apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox-lab
  template:
    metadata:
      labels:
        app: busybox-lab
    spec:
      containers:
      - name: busybox
        image: busybox